version: "3"
services:
  nginx:
    container_name: nginx-ohif
    image: ohif/viewer
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./conf/sites-enabled:/etc/nginx/sites-enabled
      - ./conf/mime.types:/etc/nginx/mime.types
      - ./conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/viewer-conf.js:/usr/share/nginx/html/app-config.js
    restart: always
